<template>
  <video
    crossorigin="true"
    playsinline
    poster="../video/poster.png"
    src="../video/preview-small.mp4"
    muted
    loop
    autoplay
    preload="metadata"
  />
</template>
